/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PostOffice.java
 *
 * Created on Nov 5, 2012, 12:12:36 PM
 */
/**
 *
 * @author alisa.maas
 */
public class PostOffice extends javax.swing.JFrame {

    /** Creates new form PostOffice */
    public PostOffice() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParticipantScrollPane = new javax.swing.JScrollPane();
        ParticipantList = new javax.swing.JList();
        ParticipantLabel = new javax.swing.JLabel();
        QueueScrollPane = new java.awt.ScrollPane();
        QueueJScrollPane = new javax.swing.JScrollPane();
        QueueText = new javax.swing.JTextPane();
        LogScrollPane = new java.awt.ScrollPane();
        LogJScrollPane = new javax.swing.JScrollPane();
        LogText = new javax.swing.JTextPane();
        TopPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        PlayPauseButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        DetailsScrollPane = new java.awt.ScrollPane();
        DetailsJScrollPane = new javax.swing.JScrollPane();
        ParticipantDetailsPanel = new javax.swing.JTextPane();
        OperationsPanel = new javax.swing.JPanel();
        promoteButton = new javax.swing.JButton();
        MessagesButton = new javax.swing.JButton();
        ResignButton = new javax.swing.JButton();
        EnterButton = new javax.swing.JButton();
        DelayButton = new javax.swing.JButton();
        LeaveButton = new javax.swing.JButton();
        imageNamePanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        PlusMinusPanel = new javax.swing.JPanel();
        PlusButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();

        setResizable(true);
        setTitle("Paxos Simulator");
        setVisible(true);
        ParticipantList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ParticipantScrollPane.setViewportView(ParticipantList);

        ParticipantLabel.setText("Participants");

        QueueText.setText("Queue/Events");
        QueueJScrollPane.setViewportView(QueueText);

        QueueScrollPane.add(QueueJScrollPane);

        LogText.setText("Log");
        LogJScrollPane.setViewportView(LogText);

        LogScrollPane.add(LogJScrollPane);

        TopPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image/home1.png"))); // NOI18N
        homeButton.setMinimumSize(new java.awt.Dimension(10, 10));
        homeButton.setPreferredSize(new java.awt.Dimension(10, 10));

        PlayPauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image/pause2.png"))); // NOI18N

        timeLabel.setText("currentTime");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(PlayPauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(timeLabel)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(PlayPauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        ParticipantDetailsPanel.setText("Participant Details.");
        DetailsJScrollPane.setViewportView(ParticipantDetailsPanel);

        DetailsScrollPane.add(DetailsJScrollPane);

        OperationsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        promoteButton.setText("Promote");

        MessagesButton.setText("Messages");

        ResignButton.setText("Resign");

        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        DelayButton.setText("Delay");

        LeaveButton.setText("Leave");

        javax.swing.GroupLayout OperationsPanelLayout = new javax.swing.GroupLayout(OperationsPanel);
        OperationsPanel.setLayout(OperationsPanelLayout);
        OperationsPanelLayout.setHorizontalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(DelayButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(EnterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(ResignButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(MessagesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(promoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );
        OperationsPanelLayout.setVerticalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperationsPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(promoteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MessagesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResignButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DelayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LeaveButton)
                .addContainerGap())
        );

        imageNamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image/profile1.png"))); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        nameLabel.setText("Name here");

        javax.swing.GroupLayout imageNamePanelLayout = new javax.swing.GroupLayout(imageNamePanel);
        imageNamePanel.setLayout(imageNamePanelLayout);
        imageNamePanelLayout.setHorizontalGroup(
            imageNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageNamePanelLayout.createSequentialGroup()
                .addGroup(imageNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imageNamePanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nameLabel))
                    .addGroup(imageNamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        imageNamePanelLayout.setVerticalGroup(
            imageNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageNamePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PlusMinusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        //PlusButton.setFont(new java.awt.Font(null, 0, 12)); // NOI18N
        PlusButton.setText("-");
        
        MinusButton.setText("+");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout PlusMinusPanelLayout = new javax.swing.GroupLayout(PlusMinusPanel);
        PlusMinusPanel.setLayout(PlusMinusPanelLayout);
        PlusMinusPanelLayout.setHorizontalGroup(
            PlusMinusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlusMinusPanelLayout.createSequentialGroup()
                .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MinusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
        PlusMinusPanelLayout.setVerticalGroup(
            PlusMinusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlusMinusPanelLayout.createSequentialGroup()
                .addGroup(PlusMinusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ParticipantLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PlusMinusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ParticipantScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QueueScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OperationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TopPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ParticipantLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(OperationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageNamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(QueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ParticipantScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PlusMinusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelayButton;
    private javax.swing.JScrollPane DetailsJScrollPane;
    private java.awt.ScrollPane DetailsScrollPane;
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton LeaveButton;
    private javax.swing.JScrollPane LogJScrollPane;
    private java.awt.ScrollPane LogScrollPane;
    private javax.swing.JTextPane LogText;
    private javax.swing.JButton MessagesButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JPanel OperationsPanel;
    private javax.swing.JTextPane ParticipantDetailsPanel;
    private javax.swing.JLabel ParticipantLabel;
    private javax.swing.JList ParticipantList;
    private javax.swing.JScrollPane ParticipantScrollPane;
    private javax.swing.JButton PlayPauseButton;
    private javax.swing.JButton PlusButton;
    private javax.swing.JPanel PlusMinusPanel;
    private javax.swing.JScrollPane QueueJScrollPane;
    private java.awt.ScrollPane QueueScrollPane;
    private javax.swing.JTextPane QueueText;
    private javax.swing.JButton ResignButton;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel imageNamePanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton promoteButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

}
